version: '3'

services:
  server:
    build: server/
    command: npx nodemon
    ports:
      - 3000:3000
      - 4000:4000
    env_file:
      - server/.env

  client:
    build: client/
    command: npm run dev
    ports:
      - 5173:5173
    depends_on:
      - server
    env_file:
      - client/.env